basePath: /api/v1
definitions:
  task.Task:
    properties:
      completed:
        type: boolean
      id:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: '@daran9'
    name: Sundaran Kumar
    url: http://daran.wordpress.com
  description: Todo API built using Go and Gin with DDD. You can visit the GitHub
    repository at https://github.com/daran9/todo-api-go
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Todo API
  version: "1.0"
paths:
  /task:
    get:
      operationId: get-all-tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Task'
      summary: get all items in the task list
    post:
      operationId: create-task
      parameters:
      - description: task data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/task.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Task'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: add a new item to the task list
  /task/{id}:
    get:
      operationId: get-task-by-id
      parameters:
      - description: task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Task'
        "404":
          description: Not Found
          schema:
            type: object
      summary: get a task item by ID
swagger: "2.0"
